In [1]:
import os

print(os.getcwd())
print(os.listdir("../data/raw"))

d:\credit-default-risk\notebooks
['credit_default.xls']

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

df = pd.read_excel("../data/raw/credit_default.xls",header=1)


display(df.head(5))

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [4]:
df.shape

(30000, 25)

In [5]:
df.columns.tolist()

['ID',
 'LIMIT_BAL',
 'SEX',
 'EDUCATION',
 'MARRIAGE',
 'AGE',
 'PAY_0',
 'PAY_2',
 'PAY_3',
 'PAY_4',
 'PAY_5',
 'PAY_6',
 'BILL_AMT1',
 'BILL_AMT2',
 'BILL_AMT3',
 'BILL_AMT4',
 'BILL_AMT5',
 'BILL_AMT6',
 'PAY_AMT1',
 'PAY_AMT2',
 'PAY_AMT3',
 'PAY_AMT4',
 'PAY_AMT5',
 'PAY_AMT6',
 'default payment next month']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,30000.0,15000.500000,8660.398374,1.0,7500.75,15000.5,22500.25,30000.0
LIMIT_BAL,30000.0,167484.322667,129747.661567,10000.0,50000.00,140000.0,240000.00,1000000.0
SEX,30000.0,1.603733,0.489129,1.0,1.00,2.0,2.00,2.0
EDUCATION,30000.0,1.853133,0.790349,0.0,1.00,2.0,2.00,6.0
MARRIAGE,30000.0,1.551867,0.521970,0.0,1.00,2.0,2.00,3.0
AGE,30000.0,35.485500,9.217904,21.0,28.00,34.0,41.00,79.0
PAY_0,30000.0,-0.016700,1.123802,-2.0,-1.00,0.0,0.00,8.0
PAY_2,30000.0,-0.133767,1.197186,-2.0,-1.00,0.0,0.00,8.0
PAY_3,30000.0,-0.166200,1.196868,-2.0,-1.00,0.0,0.00,8.0
PAY_4,30000.0,-0.220667,1.169139,-2.0,-1.00,0.0,0.00,8.0
PAY_5,30000.0,-0.266200,1.133187,-2.0,-1.00,0.0,0.00,8.0
PAY_6,30000.0,-0.291100,1.149988,-2.0,-1.00,0.0,0.00,8.0
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0
PAY_AMT1,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
PAY_AMT2,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
PAY_AMT3,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
PAY_AMT4,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
PAY_AMT5,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
PAY_AMT6,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0
default payment next month,30000.0,0.221200,0.415062,0.0,0.00,0.0,0.00,1.0

In [8]:
print("Missing values per column:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Missing values per column:
 ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

Duplicate rows: 0

In [9]:
print("\nUnique values:")
print(df.nunique())

Unique values:
ID                            30000
LIMIT_BAL                        81
SEX                               2
EDUCATION                         7
MARRIAGE                          4
AGE                              56
PAY_0                            11
PAY_2                            11
PAY_3                            11
PAY_4                            11
PAY_5                            10
PAY_6                            10
BILL_AMT1                     22723
BILL_AMT2                     22346
BILL_AMT3                     22026
BILL_AMT4                     21548
BILL_AMT5                     21010
BILL_AMT6                     20604
PAY_AMT1                       7943
PAY_AMT2                       7899
PAY_AMT3                       7518
PAY_AMT4                       6937
PAY_AMT5                       6897
PAY_AMT6                       6939
default payment next month        2
dtype: int64

In [10]:
target = "default payment next month"

In [11]:
df[target].value_counts()

default payment next month
0    23364
1     6636
Name: count, dtype: int64

In [12]:
df[target].value_counts(normalize=True)*100

default payment next month
0    77.88
1    22.12
Name: proportion, dtype: float64

In [13]:
df["SEX"].value_counts()

SEX
2    18112
1    11888
Name: count, dtype: int64

In [14]:
df["SEX"].value_counts(normalize=True)*100

SEX
2    60.373333
1    39.626667
Name: proportion, dtype: float64

In [15]:
df["EDUCATION"].value_counts()

EDUCATION
2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: count, dtype: int64

In [16]:
df["EDUCATION"].value_counts(normalize=True)*100

EDUCATION
2    46.766667
1    35.283333
3    16.390000
5     0.933333
4     0.410000
6     0.170000
0     0.046667
Name: proportion, dtype: float64

In [17]:
df["MARRIAGE"].value_counts()

MARRIAGE
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64

In [18]:
df["MARRIAGE"].value_counts(normalize=True)*100

MARRIAGE
2    53.213333
1    45.530000
3     1.076667
0     0.180000
Name: proportion, dtype: float64

In [19]:
for column in df.columns:
    print(f"\n{column}")
    print(df[column].unique()[:20])

ID
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

LIMIT_BAL
[ 20000 120000  90000  50000 500000 100000 140000 200000 260000 630000
  70000 250000 320000 360000 180000 130000 450000  60000 230000 160000]

SEX
[2 1]

EDUCATION
[2 1 3 5 4 6 0]

MARRIAGE
[1 2 3 0]

AGE
[24 26 34 37 57 29 23 28 35 51 41 30 49 39 40 27 47 33 32 54]

PAY_0
[ 2 -1  0 -2  1  3  4  8  7  5  6]

PAY_2
[ 2  0 -1 -2  3  5  7  4  1  6  8]

PAY_3
[-1  0  2 -2  3  4  6  7  1  5  8]

PAY_4
[-1  0 -2  2  3  4  5  7  6  1  8]

PAY_5
[-2  0 -1  2  3  5  4  7  8  6]

PAY_6
[-2  2  0 -1  3  6  4  7  8  5]

BILL_AMT1
[  3913   2682  29239  46990   8617  64400 367965  11876  11285      0
  11073  12261  12137  65802  70887  50614  15376 253286  38358    316]

BILL_AMT2
[  3102   1725  14027  48233   5670  57069 412023    380  14096      0
   9787  21670   6500  67369  67060  29173  18010 246536  27688    316]

BILL_AMT3
[   689   2682  13559  49291  35835  57608 445007    601  12108      0
   5535   9966   6500  65701  63561  28116  17428 194663  24489    316]

BILL_AMT4
[     0   3272  14331  28314  20940  19394 542653    221  12211   2513
   8517   6500  66782  59696  28771  18338  70074  20616  44006    560]

BILL_AMT5
[     0   3455  14948  28959  19146  19619 483003   -159  11793  13007
   1828  22287   6500  36137  56875  29531  17905   5856  11802    632]

BILL_AMT6
[     0   3261  15549  29547  19131  20024 473944    567   3719  13912
   3731  13668   2870  36894  55512  30211  19104 195599    930    316]

PAY_AMT1
[    0  1518  2000  2500 55000   380  3329  2306 21818  1000  3200  3000
 10358   316  2007 19428  5757  1973  1300  3415]

PAY_AMT2
[  689  1000  1500  2019 36681  1815 40000   601     0    12  9966  6500
  3000 10000  1537   316  3582  1473  1426  1300]

PAY_AMT3
[    0  1000  1200 10000   657 38000   432    50  8583  6500  3000  1100
  1500 75940   560  5398  1001  2044 15339  3302]

PAY_AMT4
[    0  1000  1100  9000 20239   581 13007   300 22301  6500  3000  1200
 20000  2000   632  3601  1432   500  1500 30430]

PAY_AMT5
[     0   1000   1069    689  13750   1687   1122   3738   2870   1500
   3000   1300   1650 195599    930    316   2045   1062    257   1600]

PAY_AMT6
[    0  2000  5000  1000   679   800 13770  1542    66  3640  3000  1100
 50000 33764  1820  1128   997  1012   716  2504]

default payment next month
[1 0]

In [20]:
print("\nCategorical columns:")
print(["SEX", "MARRIAGE"])

Categorical columns:
['SEX', 'MARRIAGE']

In [21]:
print("\nOrdinal columns:")
print([
    "EDUCATION",
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
])

Ordinal columns:
['EDUCATION', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']

In [22]:
print("\nNumerical columns:")
print([
    "LIMIT_BAL",
    "AGE",
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6",
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
])

Numerical columns:
['LIMIT_BAL', 'AGE', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']