In [5]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from src.feature_engineering import create_features
from src.preprocessing import create_preprocessor

In [7]:
df = pd.read_excel(
    "../data/raw/credit_default.xls",
    header=1
)

print("Original shape:", df.shape)
display(df.head())

Original shape: (30000, 25)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [8]:
target = "default payment next month"

X = df.drop(columns=[target, "ID"])
y = df[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (30000, 23)
y shape: (30000,)

In [9]:
X = create_features(X)

print("Shape after feature engineering:", X.shape)
display(X.head())

Shape after feature engineering: (30000, 35)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,AVG_BILL_AMT,AVG_PAY_AMT,MAX_BILL_AMT,MAX_PAY_AMT,DELAY_COUNT,SEVERE_DELAY_COUNT,AVG_PAY_STATUS,MAX_PAY_STATUS,PAYMENT_TO_BILL_RATIO,CREDIT_UTILIZATION
0,20000,2,2,1,24,2,2,-1,-1,-2,...,1284.000000,114.833333,3913,689,2,2,-0.333333,2,0.089434,0.195650
1,120000,2,2,2,26,-1,2,0,0,0,...,2846.166667,833.333333,3455,2000,2,2,0.500000,2,0.292791,0.022350
2,90000,2,2,2,34,0,0,0,0,0,...,16942.166667,1836.333333,29239,5000,0,0,0.000000,0,0.108388,0.324878
3,50000,2,2,1,37,0,0,0,0,0,...,38555.666667,1398.000000,49291,2019,0,0,0.000000,0,0.036259,0.939800
4,50000,1,2,1,57,-1,0,-1,0,0,...,18223.166667,9841.500000,35835,36681,0,0,-0.333333,0,0.540054,0.172340

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (24000, 35)
X_test: (6000, 35)
y_train: (24000,)
y_test: (6000,)

In [11]:
print("Training target distribution:")
print(y_train.value_counts(normalize=True))

print("\nTesting target distribution:")
print(y_test.value_counts(normalize=True))

Training target distribution:
default payment next month
0    0.778792
1    0.221208
Name: proportion, dtype: float64

Testing target distribution:
default payment next month
0    0.778833
1    0.221167
Name: proportion, dtype: float64

In [12]:
preprocessor = create_preprocessor()

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Processed X_train:", X_train_processed.shape)
print("Processed X_test:", X_test_processed.shape)

Processed X_train: (24000, 45)
Processed X_test: (6000, 45)

In [13]:
import joblib
import os

In [14]:
os.makedirs("../data/processed", exist_ok=True)

In [15]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(
    preprocessor,
    "../models/preprocessor.pkl"
)

print("Preprocessor saved successfully.")

Preprocessor saved successfully.