In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/raw/credit_default.xls",header=1)
target = "default payment next month"
display(df.head(4))

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

In [3]:
df = df.drop(columns=["ID"])

In [4]:
bill_cols = [
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6"
]

In [5]:
payment_cols = [
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

In [6]:
pay_status_cols = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

In [7]:
pay_status_cols = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

In [8]:
df["TOTAL_BILL_AMT"] = df[bill_cols].sum(axis=1)

df["TOTAL_PAY_AMT"] = df[payment_cols].sum(axis=1)

df["AVG_BILL_AMT"] = df[bill_cols].mean(axis=1)

df["AVG_PAY_AMT"] = df[payment_cols].mean(axis=1)

df["MAX_BILL_AMT"] = df[bill_cols].max(axis=1)

df["MAX_PAY_AMT"] = df[payment_cols].max(axis=1)

df["DELAY_COUNT"] = (df[pay_status_cols] > 0).sum(axis=1)

df["SEVERE_DELAY_COUNT"] = (df[pay_status_cols] >= 2).sum(axis=1)

df["AVG_PAY_STATUS"] = df[pay_status_cols].mean(axis=1)

df["MAX_PAY_STATUS"] = df[pay_status_cols].max(axis=1)

In [9]:
df["PAYMENT_TO_BILL_RATIO"] = (
    df["TOTAL_PAY_AMT"] /
    df["TOTAL_BILL_AMT"].replace(0, np.nan)
)

In [10]:
df["CREDIT_UTILIZATION"] = (
    df["BILL_AMT1"] /
    df["LIMIT_BAL"].replace(0, np.nan)
)

In [11]:
df = df.replace([np.inf, -np.inf], np.nan)

In [12]:
display(df.head(3))

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,AVG_BILL_AMT,AVG_PAY_AMT,MAX_BILL_AMT,MAX_PAY_AMT,DELAY_COUNT,SEVERE_DELAY_COUNT,AVG_PAY_STATUS,MAX_PAY_STATUS,PAYMENT_TO_BILL_RATIO,CREDIT_UTILIZATION
0,20000,2,2,1,24,2,2,-1,-1,-2,...,1284.000000,114.833333,3913,689,2,2,-0.333333,2,0.089434,0.195650
1,120000,2,2,2,26,-1,2,0,0,0,...,2846.166667,833.333333,3455,2000,2,2,0.500000,2,0.292791,0.022350
2,90000,2,2,2,34,0,0,0,0,0,...,16942.166667,1836.333333,29239,5000,0,0,0.000000,0,0.108388,0.324878

In [13]:
df.to_csv(
    "../data/processed/feature_engineered_data.csv",
    index=False
)

print(df.shape)
display(df.head())

(30000, 36)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,AVG_BILL_AMT,AVG_PAY_AMT,MAX_BILL_AMT,MAX_PAY_AMT,DELAY_COUNT,SEVERE_DELAY_COUNT,AVG_PAY_STATUS,MAX_PAY_STATUS,PAYMENT_TO_BILL_RATIO,CREDIT_UTILIZATION
0,20000,2,2,1,24,2,2,-1,-1,-2,...,1284.000000,114.833333,3913,689,2,2,-0.333333,2,0.089434,0.195650
1,120000,2,2,2,26,-1,2,0,0,0,...,2846.166667,833.333333,3455,2000,2,2,0.500000,2,0.292791,0.022350
2,90000,2,2,2,34,0,0,0,0,0,...,16942.166667,1836.333333,29239,5000,0,0,0.000000,0,0.108388,0.324878
3,50000,2,2,1,37,0,0,0,0,0,...,38555.666667,1398.000000,49291,2019,0,0,0.000000,0,0.036259,0.939800
4,50000,1,2,1,57,-1,0,-1,0,0,...,18223.166667,9841.500000,35835,36681,0,0,-0.333333,0,0.540054,0.172340